name: CI

on:
  pull_request:
    paths:
      - 'src/*'
  push:
    branches-ignore:
      - master

env:
  # Customize the dotnet build type here (Release, Debug, etc.)
  build_type: Release

jobs:
  build:
    name: ${{ matrix.profile }}
    runs-on: windows-latest
    strategy:
      matrix:
        profile: [windows-desktop, web]
        include:
          - profile: windows-desktop
            solution_path: src/Floorplan3D.Windows.OpenGL.sln
          - profile: web
            solution_path: src/Floorplan3D.Web.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET 9.0 (Web Only)
      if: ${{ matrix.profile == 'web' }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Install Wasm tools (Web Only)
      if: ${{ matrix.profile == 'web' }}
      run: dotnet workload install wasm-tools-net8
    - name: Setup Node.js (Web Only)
      if: ${{ matrix.profile == 'web' }}
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
    - name: Restore NuGet dependencies
      run: dotnet restore ${{ matrix.solution_path }}
    - name: Build
      run: dotnet build --no-restore ${{ matrix.solution_path }} --configuration ${{ env.build_type }}
    #- name: Test
    #  run: dotnet test --no-restore ${{ matrix.solution_path }}
