name: CI

on:
  pull_request:
    paths:
      - 'src/*'
  push:
    branches-ignore:
      - master

env:
  # Customize the dotnet build type here (Release, Debug, etc.)
  build_type: Release

jobs:
  build:
    name: ${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        profile: [windows-desktop, web]
        include:
          - profile: windows-desktop
            os: windows-latest
            solution_path: src/Floorplan3D.Windows.OpenGL.sln
          - profile: web
            os: ubuntu-latest 
            solution_path: src/Floorplan3D.Web.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore ${{ matrix.solution_path }}
    - name: Build
      run: dotnet build --no-restore ${{ matrix.solution_path }} --configuration ${{ env.build_type }}
    #- name: Test
    #  run: dotnet test --no-restore ${{ matrix.solution_path }}
